version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: eventhub-postgres
    environment:
      POSTGRES_DB: eventhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./chems:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: